# Generated by Django 3.1.6 on 2021-06-01 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='')),
                ('Gender', models.TextField(default='')),
                ('Address', models.TextField(default='')),
                ('PhoneNumber', models.CharField(default='', max_length=12)),
                ('EmailAddress', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.TextField(default='')),
                ('Location', models.TextField(default='')),
                ('Contact', models.CharField(default='', max_length=12)),
                ('EmpID', models.ManyToManyField(default=None, to='JMList.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ValidID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValID', models.TextField(default='')),
                ('ValNum', models.TextField(default='')),
                ('EmpID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='JMList.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EHealth', models.TextField(default='')),
                ('Maintenance', models.TextField(default='')),
                ('EmpID', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='JMList.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptName', models.TextField(default='')),
                ('DeptHead', models.TextField(default='')),
                ('EmpID', models.ManyToManyField(default=None, to='JMList.Employee')),
            ],
        ),
    ]
