# Generated by Django 3.1.6 on 2021-06-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JMList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='DeptHead',
            new_name='depthead',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='DeptName',
            new_name='deptname',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='EmpID',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='EmailAddress',
            new_name='emailaddress',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='PhoneNumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='employeeshealth',
            old_name='EHealth',
            new_name='ehealth',
        ),
        migrations.RenameField(
            model_name='employeeshealth',
            old_name='EmpID',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employeeshealth',
            old_name='Maintenance',
            new_name='maintenance',
        ),
        migrations.RenameField(
            model_name='validid',
            old_name='EmpID',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='validid',
            old_name='ValID',
            new_name='valid',
        ),
        migrations.RenameField(
            model_name='validid',
            old_name='ValNum',
            new_name='valnum',
        ),
        migrations.RenameField(
            model_name='workhistory',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='workhistory',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='workhistory',
            old_name='EmpID',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='workhistory',
            old_name='Location',
            new_name='location',
        ),
    ]
