# Generated by Django 3.1.6 on 2021-05-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JMList', '0002_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='last',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='valID',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='valNum',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='JMList.list'),
        ),
    ]
