# Generated by Django 3.1.6 on 2021-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JMList', '0004_auto_20210517_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhistory',
            name='DeptAssigned',
        ),
        migrations.AddField(
            model_name='workhistory',
            name='EmpID',
            field=models.ManyToManyField(default=None, to='JMList.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmailAddress',
            field=models.EmailField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='Contact',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.DeleteModel(
            name='EmployeesStatus',
        ),
    ]
